---
version: "2.11"
services:
  ha:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2022.12.8
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /home/ubuntu/ha:/config
      - /run/dbus:/run/dbus:ro
    devices:
     - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_71500734-if00-port0:/dev/ttyUSB1
     - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_71500734-if01-port0:/dev/ttyUSB0

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:8
    depends_on:
      ha:
        condition: service_started
      eufy-security-ws:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - 8091:8091
      - 3000:3000
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_0001-if00-port0:/dev/zwave

  eufy-security-ws:
    container_name: eufy-security-ws
    image: bropat/eufy-security-ws:1.3.0
    depends_on:
      ha:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./eufy_data:/data
    environment:
      - COUNTRY=US
      - USERNAME=${EUFY_USER}
      - PASSWORD=${EUFY_PASS}
      - TRUSTED_DEVICE_NAME=HomeAss
    ports:
      - 3001:3000

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    depends_on:
      ha:
        condition: service_started
    restart: unless-stopped
    volumes:
      - /storage/mosquitto:/mosquitto
      - /storage/mosquitto/data:/mosquitto/data
      - /storage/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001 

  # appdaemon:
  #   container_name: appdaemon
  #   image: acockburn/appdaemon:latest
  #   depends_on:
  #     ha:
  #       condition: service_started
  #   restart: unless-stopped
  #   network_mode: host
  #   #entrypoint: ./dockerStart.sh
  #   volumes:
  #     - ./ha/appdaemon:/conf
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - HA_URL=${HA_URL}
  #     - DASH_URL=${DASH_URL}
  #     - TOKEN=${HA_TOKEN}
  #   ports:
  #     - 5050:5050