esphome:
  name: down-hallway-light-sensor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Down-Hallway-Light-Sensor"
    password: !secret ap_password

captive_portal:

switch:
  - platform: restart
    name: "down_hallway_light_sensor Restart"
    
# sensor:
#   - platform: adc
#     pin: A0
#     name: "Down Hallway Light Sensor"
#     update_interval: 10s
#     #unit_of_measurement: lux
#     # filters:
#     #   - lambda: |-
#     #       return (x / 10000.0) * 2000000.0;
    
# invert value so off = low light
binary_sensor:
  - platform: gpio
    name: "Down Hallway Light Sensor"
    pin: D5
    filters:
      - invert:
