esphome:
  name: leaving-off-all

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
      
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Leaving-Off-All Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# input button on D7
# output led on D6

# set LED switch entry
switch:
  - platform: gpio
    pin: D6
    name: "LED D6"
    id: gpio_d6
  - platform: restart
    name: "leaving_off_all Restart"

binary_sensor:
  - platform: gpio
    name: "button1"
    pin: D5
    on_press:
      then:
        - switch.turn_on: gpio_d6
        - delay: 0.5s
        - switch.turn_off: gpio_d6
        - delay: 0.5s
        - switch.turn_on: gpio_d6
        - delay: 0.5s
        - switch.turn_off: gpio_d6
        - delay: 0.5s
        - switch.turn_on: gpio_d6
        - delay: 0.5s
        - switch.turn_off: gpio_d6
