esphome:
  name: micky_elmo
  
esp8266:
  board: nodemcuv2
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Micky Elmo Fallback Hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
output:
  - platform: gpio
    pin: D7
    id: 'generic_out'
    
# set LED switch entry
switch:
  - platform: gpio
    pin: D7
    name: "LED D7"
    id: gpio_d7
  - platform: output
    name: "micky_elmo_output"
    id: 'micky_elmo_output'
    output: 'generic_out'

binary_sensor:
  - platform: gpio
    name: "button1"
    pin: D5
    on_press:
      then:
        - switch.turn_on: gpio_d7
        - delay: 0.5s
        - switch.turn_off: gpio_d7
        - delay: 0.5s
        - switch.turn_on: gpio_d7
        - delay: 0.5s
        - switch.turn_off: gpio_d7
        - delay: 0.5s
        - switch.turn_on: gpio_d7
        - delay: 0.5s
        - switch.turn_off: gpio_d7
    on_click:
      min_length: 2000ms
      max_length: 10000ms
      then:
        - switch.toggle: micky_elmo_output
  - platform: gpio
    name: "button2"
    pin: D6
    on_press:
      then:
        - switch.turn_on: gpio_d7
        - delay: 0.5s
        - switch.turn_off: gpio_d7
        - delay: 0.5s
        - switch.turn_on: gpio_d7
        - delay: 0.5s
        - switch.turn_off: gpio_d7
        - delay: 0.5s
        - switch.turn_on: gpio_d7
        - delay: 0.5s
        - switch.turn_off: gpio_d7
    on_click:
      min_length: 2000ms
      max_length: 10000ms
      then:
        - switch.toggle: micky_elmo_output