esphome:
  name: shade-center

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # manual_ip:
  #   # Set this to the IP of the ESP
  #   static_ip: 192.168.0.146
  #   gateway: 192.168.0.1
  #   subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Shade-Center Fallback Hotspot"
    password: !secret ap_password

captive_portal:

binary_sensor:
  - platform: gpio
    name: "shade_center"
    pin: D5

switch:
  - platform: restart
    name: "shade_center Restart"