esphome:
  name: shade-left

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Shade-Left Fallback Hotspot"
    password: !secret ap_password

captive_portal:

binary_sensor:
  - platform: gpio
    name: "shade_left"
    pin: D5
    
switch:
  - platform: restart
    name: "shade_left Restart"