esphome:
  name: stairs-up-hallway-sensor

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stairs Up Hallway Sensor"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
# input motion on D7
# input motion on D6
    
binary_sensor:
  - platform: gpio
    name: "stairs_up_motion"
    device_class: motion
    pin: D5
  - platform: gpio
    name: "stairs_motion"
    device_class: motion
    pin: D6
  - platform: gpio
    name: "up_hallway_motion"
    device_class: motion
    pin: D7
    
switch:
  - platform: restart
    name: "stairs_up_hallway Restart"