---
version: "2.1"
services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - USER=<username> #optional
      - PASS=<password> #optional
#      - TRANSMISSION_WEB_HOME= #optional
#      - WHITELIST= #optional
#      - PEERPORT= #optional
#      - HOST_WHITELIST= #optional
    volumes:
      - ./transmission/data:/config
      - ./transmission/completed:/downloads
      - ./transmission/watch:/watch
    ports:
      - 9091:9091